# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Term-Clui
version:      1.40
version_from: Clui.pm
installdirs:  site
requires:

distribution_type: module
generated_by: /usr/bin/vim
